In [1]:
import numpy as np
from numpy.core.fromnumeric import transpose
data = np.array(np.random.uniform(size=50))
data = data.reshape(10,5)
##add new column
data[:,-2] = [0,0,0,0,1,1,1,1,0,1]
X_s = data[np.array(np.where(data[:,-2]==1))[0].flatten()][:,:-1]
X_ns = data[np.array(np.where(data[:,-2]==0))[0].flatten()][:,:-1]
X_s
y_sensitive = data[np.array(np.where(data[:,-2]==1))[0].flatten(), -1]
y_nonsensitive =data[np.array(np.where(data[:,-2]==0))[0].flatten(), -1]
y_sensitive

X = data[:,:-2]
Z = data[:,-2]
y = data[:,-1]




In [2]:
from numpy.core.fromnumeric import transpose
first_system = np.matmul(transpose(Z - Z.mean()), X)
first_system

array([0.58321574, 0.7571967 , 0.5751372 ])

In [3]:
transpose(Z - Z.mean())

array([-0.5, -0.5, -0.5, -0.5,  0.5,  0.5,  0.5,  0.5, -0.5,  0.5])

In [5]:
class SVM():
  def __init__(self, N, k):
    self.theta = np.array(np.random.uniform(size=k)).reshape(-1, 1)
    self.phi = np.array(np.random.uniform(size=N))
  
  def covariance_upper_constraint(self, X, Z, c):
    return ((-1) * np.matmul(np.matmul(transpose(Z - Z.mean()), X), self.theta)) + c

  def covariance_lower_constraint(self, X, Z, c):
    print('X: ',X)
    print('Z: ',Z)
    print('c: ',c)
    return (np.matmul(np.matmul(transpose(Z - Z.mean()), X), self.theta)) + c   
  
  def loss_fn(self, C):
    return LA.norm(self.theta,2) + sum(self.phi) * C


In [38]:
#svm.covariance_upper_constraint(Z,X,0.8)
#((-1) * np.matmul(np.matmul(transpose(Z - Z.mean()), X), svm.theta)) + 0.8
np.matmul(np.matmul(transpose(Z - Z.mean()), X), svm.theta)

array([-0.17500339])

In [51]:
svm.covariance_upper_constraint(X, Z, 0.8)

array([0.74777136])

In [67]:
constraint(X, Z, 0.8, svm.theta, False)

X:  [[0.64795095 0.14951949 0.14875985]
 [0.48253649 0.67684775 0.60495505]
 [0.29982938 0.39817412 0.00229019]
 [0.22921604 0.39389235 0.95443168]
 [0.77636584 0.46861933 0.42288006]
 [0.62932365 0.46939001 0.02835344]
 [0.61559463 0.0338504  0.56138914]
 [0.55820798 0.78631    0.06884757]
 [0.07169249 0.62316738 0.99080872]
 [0.15717875 0.96518288 0.3829214 ]]
Z:  [0. 0. 0. 0. 1. 1. 1. 1. 0. 1.]
c:  0.8
theta:  [[0.06811769]
 [0.58247547]
 [0.00303955]]


array([0.6273312])

In [7]:
#https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html
#https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize
#https://scipy-lectures.org/advanced/mathematical_optimization/auto_examples/plot_non_bounds_constraints.html
import scipy
from scipy.optimize import minimize
from numpy import linalg as LA

k=3
N = 10
def upper_theta_constraint(params, X, Z, c, k):
  theta = params[:k]
  #print('X: ',X.shape)
  #print('Z: ',Z.shape)
  #print('c: ',c)
  #print('theta: ', theta.shape)
  #if flag: print('here')
  return ((-1/len(Z)) * np.matmul(np.matmul(transpose(Z - Z.mean()), X), theta)) + c

def lower_theta_constraint(params, X, Z, c, k):
  theta = params[:k]
  #print('X: ',X.shape)
  #print('Z: ',Z.shape)
  #print('c: ',c)
  #print('theta: ', theta.shape)
  #if flag: print('here')
  return ((np.matmul(np.matmul(transpose(Z - Z.mean()), X), theta))/len(Z)) + c  

def svm_loss(params,C,k):
  theta = params[:k]
  phi = params[k:]
  return LA.norm(theta,2) + sum(phi) * C

def phi_constraint(params, x, y, k):
  theta = params[:k]
  phi = params[k:]

  return

svm = SVM(N,k)
print(svm.theta)
scipy.optimize.minimize(svm_loss, args=(0.9, k), x0=np.append(svm.theta.flatten(), svm.phi.flatten()),
                        method='SLSQP', 
                        constraints=({'type': 'ineq', 'fun': upper_theta_constraint, 'args': (X, Z , 0.8, k)},
                                     {'type': 'ineq', 'fun': lower_theta_constraint, 'args': (X, Z , 0.8, k)}),
                        options={"maxiter": 100000})
###TODO: these numbers feel a little too high -- am I passing in the right x0??
##TODO: phi constraint???? how to write this?

[[0.84536759]
 [0.38486883]
 [0.24819701]]


     fun: -145874740.8709746
     jac: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
 message: 'Optimization terminated successfully'
    nfev: 264
     nit: 18
    njev: 18
  status: 0
 success: True
       x: array([ -4153636.41056982,   1813821.55619263,   1823995.57480676,
       -16751151.97215278, -16751151.95360281, -16751151.96178035,
       -16751152.65289018, -16751152.83606847, -16751152.4153125 ,
       -16751150.82807123, -16751160.48950713, -16751160.43116862,
       -16751163.05594579])

In [101]:
k=3
N = 10
def upper_theta_constraint(theta, X, Z, c, k):
  #theta = params[:k]
  #print('X: ',X.shape)
  #print('Z: ',Z.shape)
  #print('c: ',c)
  #print('theta: ', theta.shape)
  #if flag: print('here')
  return ((-1) * np.matmul(np.matmul(transpose(Z - Z.mean()), X), theta)) + c

def lower_theta_constraint(theta, X, Z, c, k):
  #theta = params[:k]
  #print('X: ',X.shape)
  #print('Z: ',Z.shape)
  #print('c: ',c)
  #print('theta: ', theta.shape)
  #if flag: print('here')
  return (np.matmul(np.matmul(transpose(Z - Z.mean()), X), theta)) + c  

def svm_loss(theta, phi,C,k):
  return LA.norm(theta,2) + sum(phi) * C

def phi_constraint(params, x, y, k):
  theta = params[:k]
  phi = params[k:]

  return

svm = SVM(N,k)
print(svm.theta)
scipy.optimize.minimize(svm_loss, args=(svm.phi, 0.9, k), x0=svm.theta,
                        method='SLSQP', 
                        constraints=({'type': 'ineq', 'fun': upper_theta_constraint, 'args': (X, Z , 0.8, k)},
                                     {'type': 'ineq', 'fun': lower_theta_constraint, 'args': (X, Z , 0.8, k)}),
                        options={"maxiter": 100000})

[[0.13650027]
 [0.93175268]
 [0.00955904]]


     fun: 4.697482699971658
     jac: array([0.14569044, 0.98739517, 0.06189585])
 message: 'Optimization terminated successfully'
    nfev: 28
     nit: 5
    njev: 5
  status: 0
 success: True
       x: array([8.20579576e-05, 5.60245250e-04, 5.23616096e-06])

In [91]:
np.append(svm.theta.flatten(), svm.phi.flatten())

array([0.77822744, 0.02718473, 0.37207802, 0.73303847, 0.99847787,
       0.56687995, 0.17478334, 0.30383969, 0.9056702 , 0.86278665,
       0.78579081, 0.58692222, 0.33628126])

In [90]:
svm.theta.flatten().np.concatenate(svm.phi.flatten())

AttributeError: ignored

In [20]:
for i in svm.theta :
  print(i*i)
0.55474208  + 0.06968351
np.random.uniform(size=2)

[0.55474208]
[0.06968351]


array([0.66614572, 0.28922723])

In [23]:
from numpy import linalg as LA
svm = SVM(10,2)
LA.norm(svm.theta,2)

1.0842882373007432